services:
  # PostgreSQL数据库服务 - 使用简化版本
  db:
    build:
      context: ./db/postgresql
      dockerfile: Dockerfile.simple
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  # Redis缓存服务 - 使用简化版本
  redis:
    build:
      context: ./db/redis
      dockerfile: Dockerfile.simple
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Django后端应用
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - ./media:/app/media
      - ./static:/app/static
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - REDIS_URL=redis://redis:6379/0

  # Vue前端应用
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api

volumes:
  postgres_data:
  redis_data: 