services:
  # PostgreSQL database service
  db:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/postgres:14.15
    pull_policy: never
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "15432:5432"  # 使用15432端口而不是5432

  # Redis cache service
  redis:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/redis:alpine
    pull_policy: never
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Django backend application
  backend:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/python:3.10-slim
    pull_policy: never
    working_dir: /app
    command: >
      sh -c "cd /app && 
             pip install --no-index --find-links=/offline-packages --find-links=/offline-packages/py3 -r requirements.txt &&
             python manage.py makemigrations &&
             python manage.py migrate --noinput || echo 'Migration error, continuing anyway...' &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - ./media:/app/media
      - ./static:/app/static
      - ./offline-resources/python-packages:/offline-packages
      - ./requirements.txt:/app/requirements.txt
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - REDIS_URL=redis://redis:6379/0

  # Vue frontend application
  frontend:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/node:18-alpine
    pull_policy: never
    working_dir: /app
    command: sh /start-frontend.sh
    volumes:
      - ./frontend:/app
      - ./offline-resources/npm-packages:/npm-packages
      - ./start-frontend.sh:/start-frontend.sh
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api

volumes:
  postgres_data:
  redis_data: 