# Generated by Django 4.2.10 on 2025-04-11 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='项目代号')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('paused', '已暂停'), ('archived', '已归档')], default='in_progress', max_length=20, verbose_name='项目状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('recsubmit_date', models.DateField(blank=True, null=True, verbose_name='最近提交日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('cgtw_project_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='CGTeamwork项目ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('animation', '动画'), ('post', '后期'), ('fx', '解算'), ('producer', '制片'), ('model', '模型')], max_length=20, verbose_name='部门')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_departments', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目部门关联',
                'verbose_name_plural': '项目部门关联',
                'unique_together': {('project', 'department')},
            },
        ),
    ]
