FROM registry.cn-hangzhou.aliyuncs.com/library/redis:alpine

# 设置时区
ENV TZ=Asia/Shanghai

# 复制自定义配置文件（可选）
# COPY redis.conf /usr/local/etc/redis/redis.conf

# 使用自定义配置文件启动（可选）
# CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ] 