FROM alpine:3.16

RUN apk add --no-cache postgresql postgresql-client

ENV PGDATA=/var/lib/postgresql/data

RUN mkdir -p "$PGDATA" && chown -R postgres:postgres "$PGDATA" && chmod 700 "$PGDATA"

# 添加PostgreSQL初始化脚本
COPY ./init-scripts/ /docker-entrypoint-initdb.d/

# 切换到postgres用户
USER postgres

# 初始化数据库
RUN initdb -D "$PGDATA"

# 配置监听
RUN echo "host all all 0.0.0.0/0 md5" >> "$PGDATA/pg_hba.conf" && \
    echo "listen_addresses='*'" >> "$PGDATA/postgresql.conf"

EXPOSE 5432

CMD ["postgres"] 