# Generated by Django 4.2.10 on 2024-04-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_image',
            field=models.BooleanField(default=False, verbose_name='是否为图片'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='thumbnail_path',
            field=models.FileField(blank=True, null=True, upload_to='@attachments/thumbnails/%Y/%m/%d/', verbose_name='缩略图路径'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_path',
            field=models.FileField(upload_to='@attachments/%Y/%m/%d/', verbose_name='文件路径'),
        ),
    ] 