# Generated by Django 4.2.10 on 2025-04-11 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_notes',
            field=models.TextField(blank=True, null=True, verbose_name='注册备注'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='注册状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('animation', '动画'), ('post', '后期'), ('fx', '解算'), ('producer', '制片'), ('model', '模型')], max_length=20, null=True, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '系统管理员'), ('supervisor', '主管'), ('leader', '带片'), ('producer', '制片'), ('artist', '艺术家')], default='artist', max_length=20, verbose_name='角色'),
        ),
    ]
