# Generated by Django 4.2.10 on 2025-04-11 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_device_code'),
        ('users', '0002_user_approval_date_user_approved_by_and_more'),
    ]

    operations = [
    ]
