# Generated by Django 4.2.10 on 2025-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20250411_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('animation', '动画'), ('post', '后期'), ('fx', '解算'), ('producer', '制片'), ('model', '模型'), ('tech', '技术')], max_length=20, null=True, verbose_name='部门'),
        ),
    ]
