# Generated by Django 4.2.10 on 2025-04-11 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_code', models.CharField(max_length=100, verbose_name='镜头编号')),
                ('department', models.CharField(choices=[('DH', '动画'), ('JS', '解算'), ('HQ', '后期')], default='DH', max_length=2, verbose_name='所属部门')),
                ('prom_stage', models.CharField(choices=[('LAY', 'Layout'), ('BLK', 'Block'), ('ANI', 'Animation'), ('PASS', 'Pass')], default='LAY', max_length=4, verbose_name='推进阶段')),
                ('status', models.CharField(choices=[('waiting', '等待开始'), ('in_progress', '正在制作'), ('submit_review', '提交内审'), ('revising', '正在修改'), ('internal_approved', '内审通过'), ('client_review', '客户审核'), ('client_rejected', '客户退回'), ('client_approved', '客户通过'), ('client_revision', '客户返修'), ('deleted_merged', '已删除或合并'), ('suspended', '暂停制作'), ('completed', '已完结')], default='waiting', max_length=20, verbose_name='制作状态')),
                ('duration_frame', models.IntegerField(default=0, verbose_name='时长(帧)')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('last_submit_date', models.DateField(blank=True, null=True, verbose_name='最近提交日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='元数据')),
                ('cgtw_task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='CGTeamwork任务ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shots', to=settings.AUTH_USER_MODEL, verbose_name='制作者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '镜头',
                'verbose_name_plural': '镜头',
                'ordering': ['shot_code'],
            },
        ),
        migrations.CreateModel(
            name='ShotNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='备注内容')),
                ('is_important', models.BooleanField(default=False, verbose_name='重要提示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='shots.shot', verbose_name='镜头')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_notes', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
            ],
            options={
                'verbose_name': '镜头备注',
                'verbose_name_plural': '镜头备注',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shot',
            index=models.Index(fields=['shot_code'], name='shots_shot_shot_co_a1b55f_idx'),
        ),
        migrations.AddIndex(
            model_name='shot',
            index=models.Index(fields=['status'], name='shots_shot_status_dcf03a_idx'),
        ),
        migrations.AddIndex(
            model_name='shot',
            index=models.Index(fields=['department'], name='shots_shot_departm_6b841a_idx'),
        ),
        migrations.AddIndex(
            model_name='shot',
            index=models.Index(fields=['deadline'], name='shots_shot_deadlin_ba0e5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shot',
            unique_together={('project', 'shot_code')},
        ),
    ]
