# Generated by Django 4.2.10 on 2025-04-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='duration_frame',
            field=models.IntegerField(default=0, verbose_name='时长(帧)'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='prom_stage',
            field=models.CharField(choices=[('LAY', 'Layout'), ('BLK', 'Block'), ('ANI', 'Animation'), ('PASS', 'Pass')], default='LAY', max_length=4, verbose_name='推进阶段'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='status',
            field=models.CharField(choices=[('waiting', '等待开始'), ('in_progress', '正在制作'), ('submit_review', '提交内审'), ('revising', '正在修改'), ('internal_approved', '内审通过'), ('client_review', '客户审核'), ('client_rejected', '客户退回'), ('client_approved', '客户通过'), ('client_revision', '客户返修'), ('deleted_merged', '已删除或合并'), ('suspended', '暂停制作'), ('completed', '已完结')], default='waiting', max_length=20, verbose_name='制作状态'),
        ),

    ]
