# Generated by Django 4.2.10 on 2025-04-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0002_auto_20250411_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='framepersecond',
            field=models.IntegerField(default=25, verbose_name='帧率'),
        ),
    ]
