# Generated by Django 4.2.10 on 2025-04-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0003_shot_framepersecond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='department',
            field=models.CharField(choices=[('DH', '动画'), ('JS', '解算'), ('HQ', '后期'), ('MX', '模型')], default='DH', max_length=2, verbose_name='所属部门'),
        ),
    ]
