# Generated by Django 4.2.10 on 2025-04-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0004_alter_shot_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='department',
            field=models.CharField(choices=[('animation', '动画'), ('post', '后期'), ('fx', '解算'), ('producer', '制片'), ('model', '模型')], default='animation', max_length=20, verbose_name='所属部门'),
        ),
    ]
