# Generated by Django 4.2.10 on 2025-04-13 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0006_alter_shot_department'),
        ('shots', 'add_shot_note_attachment'),
    ]

    operations = [
    ]
