# Generated by Django 4.2.10 on 2024-04-13 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotNoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='@attachments/%Y/%m/%d/', verbose_name='文件路径')),
                ('thumbnail_path', models.FileField(blank=True, null=True, upload_to='@attachments/thumbnails/%Y/%m/%d/', verbose_name='缩略图路径')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.PositiveIntegerField(help_text='文件大小(字节)', verbose_name='文件大小')),
                ('mime_type', models.CharField(max_length=100, verbose_name='文件类型')),
                ('is_image', models.BooleanField(default=False, verbose_name='是否为图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='shots.shotnote', verbose_name='关联备注')),
            ],
            options={
                'verbose_name': '备注附件',
                'verbose_name_plural': '备注附件',
            },
        ),
    ] 